# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
schedules = Schedule.create([{
	"away": "Canterbury Red Devils",
	"awayAbr": "CRD",
	"prettyDate": "Friday, May 26th, 6:50pm",
	"home": "Skycity Stampede",
	"homeAbr": "STP",
	"leagueGame": "Game 1",
	"venue": "Queenstown Ice Arena",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5"
}, {
	"away": "Canterbury Red Devils",
	"awayAbr": "CRD",
	"prettyDate": "Saturday, May 27th, 6:50pm",
	"home": "Skycity Stampede",
	"homeAbr": "STP",
	"leagueGame": "Game 2",
	"venue": "Queenstown Ice Arena",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5"
}, {
	"away": "Botany Swarm",
	"awayAbr": "BSW",
	"date": "27/05/2017",
	"prettyDate": "Saturday, May 27th, 4:30pm",
	"home": "West Auckland Admirals",
	"homeAbr": "WAA",
	"leagueGame": "Game 3",
	"venue": "Paradice Avondale",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69"
}, {
	"away": "Botany Swarm",
	"awayAbr": "BSW",
	"date": "28/05/2017",
	"prettyDate": "Sunday, May 28th, 4:30pm",
	"home": "West Auckland Admirals",
	"homeAbr": "WAA",
	"leagueGame": "Game 4",
	"venue": "Paradice Avondale",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69"
}, {
	"away": "West Auckland Admirals",
	"awayAbr": "WAA",
	"prettyDate": "Saturday, June 10th, 4:30pm",
	"home": "Dunedin Thunder",
	"homeAbr": "THU",
	"leagueGame": "Game 5",
	"venue": "Dunedin Ice Stadium",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee"
}, {
	"away": "West Auckland Admirals",
	"awayAbr": "WAA",
	"prettyDate": "Saturday, June 11th, 4:30pm",
	"home": "Dunedin Thunder",
	"homeAbr": "THU",
	"leagueGame": "Game 6",
	"venue": "Dunedin Ice Stadium",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee"
}, {
	"away": "Canterbury Red Devils",
	"awayAbr": "CRD",
	"date": "10/06/2017",
	"prettyDate": "Saturday, June 10th, 4:45pm",
	"home": "Botany Swarm",
	"homeAbr": "BSW",
	"leagueGame": "Game 7",
	"venue": "Paradice Botany",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5"
}, {
	"away": "Canterbury Red Devils",
	"awayAbr": "CRD",
	"date": "11/06/2017",
	"prettyDate": "Sunday, June 11th, 4:45pm",
	"home": "Botany Swarm",
	"homeAbr": "BSW",
	"leagueGame": "Game 8",
	"venue": "Paradice Botany",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5"
}, {
	"away": "Skycity Stampede",
	"awayAbr": "STP",
	"prettyDate": "Saturday, June 17th, 4:40pm",
	"home": "Dunedin Thunder",
	"homeAbr": "THU",
	"leagueGame": "Game 9",
	"venue": "Dunedin Ice Stadium",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c"
}, {
	"away": "Skycity Stampede",
	"awayAbr": "STP",
	"prettyDate": "Sunday, June 18th, 4:40pm",
	"home": "Dunedin Thunder",
	"homeAbr": "THU",
	"leagueGame": "Game 10",
	"venue": "Dunedin Ice Stadium",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c"
}, {
	"away": "Canterbury Red Devils",
	"awayAbr": "CRD",
	"prettyDate": "Saturday, June 17th, 4:30pm",
	"home": "West Auckland Admirals",
	"homeAbr": "WAA",
	"leagueGame": "Game 11",
	"venue": "Paradice Avondale",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5"
}, {
	"away": "Canterbury Red Devils",
	"awayAbr": "CRD",
	"prettyDate": "Sunday, June 18th, 4:30pm",
	"home": "West Auckland Admirals",
	"homeAbr": "WAA",
	"leagueGame": "Game 12",
	"venue": "Paradice Avondale",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5"
}, {
	"away": "Botany Swarm",
	"awayAbr": "BSW",
	"prettyDate": "Friday, June 23rd, 7:40pm",
	"home": "Skycity Stampede",
	"homeAbr": "STP",
	"leagueGame": "Game 13",
	"venue": "Queenstown Ice Arena",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69"
}, {
	"away": "Botany Swarm",
	"awayAbr": "BSW",
	"prettyDate": "Saturday, June 24th, 6:50pm",
	"home": "Skycity Stampede",
	"homeAbr": "STP",
	"leagueGame": "Game 14",
	"venue": "Queenstown Ice Arena",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69"
}, {
	"away": "Dunedin Thunder",
	"awayAbr": "THU",
	"prettyDate": "Saturday, June 24th, 4:45pm",
	"home": "Canterbury Red Devils",
	"homeAbr": "CRD",
	"leagueGame": "Game 15",
	"venue": "Christchurch Alpine Ice",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be"
}, {
	"away": "Dunedin Thunder",
	"awayAbr": "THU",
	"prettyDate": "Sunday, June 25th, 4:45pm",
	"home": "Canterbury Red Devils",
	"homeAbr": "CRD",
	"leagueGame": "Game 16",
	"venue": "Christchurch Alpine Ice",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be"
}, {
	"away": "Skycity Stampede",
	"awayAbr": "STP",
	"prettyDate": "Saturday, July 1st, 4:30pm",
	"home": "West Auckland Admirals",
	"homeAbr": "WAA",
	"leagueGame": "Game 17",
	"venue": "Paradice Avondale",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c"
}, {
	"away": "Skycity Stampede",
	"awayAbr": "STP",
	"prettyDate": "Sunday, July 2nd, 4:30pm",
	"home": "West Auckland Admirals",
	"homeAbr": "WAA",
	"leagueGame": "Game 18",
	"venue": "Paradice Avondale",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c"
}, {
	"away": "Botany Swarm",
	"awayAbr": "BSW",
	"prettyDate": "Saturday, July 1st, 4:30pm",
	"home": "Dunedin Thunder",
	"homeAbr": "THU",
	"leagueGame": "Game 19",
	"venue": "Dunedin Ice Stadium",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69"
}, {
	"away": "Botany Swarm",
	"awayAbr": "BSW",
	"prettyDate": "Sunday, July 2nd, 4:30pm",
	"home": "Dunedin Thunder",
	"homeAbr": "THU",
	"leagueGame": "Game 20",
	"venue": "Dunedin Ice Stadium",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69"
}, {
	"away": "Dunedin Thunder",
	"awayAbr": "THU",
	"prettyDate": "Friday, July 7th, 6:50pm",
	"home": "Skycity Stampede",
	"homeAbr": "STP",
	"leagueGame": "Game 21",
	"venue": "Queenstown Ice Arena",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be"
}, {
	"away": "Dunedin Thunder",
	"awayAbr": "THU",
	"prettyDate": "Saturday, July 8th, 6:50pm",
	"home": "Skycity Stampede",
	"homeAbr": "STP",
	"leagueGame": "Game 22",
	"venue": "Queenstown Ice Arena",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be"
}, {
	"away": "West Auckland Admirals",
	"awayAbr": "WAA",
	"prettyDate": "Saturday, July 8th, 4:35pm",
	"home": "Canterbury Red Devils",
	"homeAbr": "CRD",
	"leagueGame": "Game 23",
	"venue": "Christchurch Alpine Ice",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee"
}, {
	"away": "West Auckland Admirals",
	"awayAbr": "WAA",
	"prettyDate": "Sunday, July 9th 2017, 4:30pm",
	"home": "Canterbury Red Devils",
	"homeAbr": "CRD",
	"leagueGame": "Game 24",
	"venue": "Christchurch Alpine Ice",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee"
}, {
	"away": "West Auckland Admirals",
	"awayAbr": "WAA",
	"prettyDate": "Friday, July 14th, 6:50pm",
	"home": "Skycity Stampede",
	"homeAbr": "STP",
	"leagueGame": "Game 25",
	"venue": "Queenstown Ice Arena",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee"
}, {
	"away": "West Auckland Admirals",
	"awayAbr": "WAA",
	"prettyDate": "Saturday, July 15th, 6:50pm",
	"home": "Skycity Stampede",
	"homeAbr": "STP",
	"leagueGame": "Game 26",
	"venue": "Queenstown Ice Arena",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee"
}, {
	"away": "Dunedin Thunder",
	"awayAbr": "THU",
	"prettyDate": "Sunday, July 16th, 4:45pm",
	"home": "Botany Swarm",
	"homeAbr": "BSW",
	"leagueGame": "Game 27",
	"venue": "Paradice Botany",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be"
}, {
	"away": "Dunedin Thunder",
	"awayAbr": "THU",
	"prettyDate": "Saturday, July 22nd, 4:45pm",
	"home": "Botany Swarm",
	"homeAbr": "BSW",
	"leagueGame": "Game 28",
	"venue": "Paradice Botany",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be"
}, {
	"away": "Skycity Stampede",
	"awayAbr": "STP",
	"prettyDate": "Saturday, July 22nd, 4:45pm",
	"home": "Botany Swarm",
	"homeAbr": "BSW",
	"leagueGame": "Game 29",
	"venue": "Paradice Botany",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c"
}, {
	"away": "Skycity Stampede",
	"awayAbr": "STP",
	"prettyDate": "Sunday, July 23rd, 4:45pm",
	"home": "Botany Swarm",
	"homeAbr": "BSW",
	"leagueGame": "Game 30",
	"venue": "Paradice Botany",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c"
}, {
	"away": "Canterbury Red Devils",
	"awayAbr": "CRD",
	"prettyDate": "Saturday, July 22nd 2017, 4:45pm",
	"home": "Dunedin Thunder",
	"homeAbr": "THU",
	"leagueGame": "Game 31",
	"venue": "Dunedin Ice Stadium",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5"
}, {
	"away": "Canterbury Red Devils",
	"awayAbr": "CRD",
	"prettyDate": "Sunday, July 23nd 2017, 4:45pm",
	"home": "Dunedin Thunder",
	"homeAbr": "THU",
	"leagueGame": "Game 32",
	"venue": "Dunedin Ice Stadium",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5"
}, {
	"away": "Dunedin Thunder",
	"awayAbr": "THU",
	"prettyDate": "Saturday July 29th, 4:45pm",
	"home": "West Auckland Admirals",
	"homeAbr": "WAA",
	"leagueGame": "Game 33",
	"venue": "Paradice Avondale",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be"
}, {
	"away": "Dunedin Thunder",
	"awayAbr": "THU",
	"prettyDate": "Sunday July 30th, 4:45pm",
	"home": "West Auckland Admirals",
	"homeAbr": "WAA",
	"leagueGame": "Game 34",
	"venue": "Paradice Avondale",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/thunder.png?alt=media&token=74c89295-bd10-4b54-b782-8e58b34036be"
}, {
	"away": "Botany Swarm",
	"awayAbr": "BSW",
	"prettyDate": "Saturday, July 29th, 4:45pm",
	"home": "Canterbury Red Devils",
	"homeAbr": "CRD",
	"leagueGame": "Game 35",
	"venue": "Christchurch Alpine Ice",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69"
}, {
	"away": "Botany Swarm",
	"awayAbr": "BSW",
	"prettyDate": "Sunday, July 30th, 4:45pm",
	"home": "Canterbury Red Devils",
	"homeAbr": "CRD",
	"leagueGame": "Game 36",
	"venue": "Christchurch Alpine Ice",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69"
}, {
	"away": "Skycity Stampede",
	"awayAbr": "STP",
	"prettyDate": "Saturday, August 5th, 4:45pm",
	"home": "Canterbury Red Devils",
	"homeAbr": "CRD",
	"leagueGame": "Game 37",
	"venue": "Christchurch Alpine Ice",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c"
}, {
	"away": "Skycity Stampede",
	"awayAbr": "STP",
	"prettyDate": "Sunday, August 6th, 4:45pm",
	"home": "Canterbury Red Devils",
	"homeAbr": "CRD",
	"leagueGame": "Game 38",
	"venue": "Christchurch Alpine Ice",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/devils.png?alt=media&token=b2f7e89b-0882-4c4f-b09d-33cbb2ddd5b5",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/stampede.png?alt=media&token=a099d85f-5eca-4ed9-a823-a7eff26e425c"
}, {
	"away": "West Auckland Admirals",
	"awayAbr": "WAA",
	"prettyDate": "Saturday August 5th, 4:45pm",
	"home": "Botany Swarm",
	"homeAbr": "BSW",
	"leagueGame": "Game 39",
	"venue": "Paradice Botany",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee"
}, {
	"away": "West Auckland Admirals",
	"awayAbr": "WAA",
	"prettyDate": "Sunday August 6th, 4:45pm",
	"home": "Botany Swarm",
	"homeAbr": "BSW",
	"leagueGame": "Game 40",
	"venue": "Paradice Botany",
	"homeLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/swarm.png?alt=media&token=78ca16e2-6101-4a14-8b8f-54bc9862bd69",
	"awayLogo": "https://firebasestorage.googleapis.com/v0/b/nzihl-game-center.appspot.com/o/admirals.png?alt=media&token=c2d26473-e8f7-45b7-8ddd-b304f7e37bee"
}])

p "created #{Schedule.count} games"

players = Player.create([{
  "name": "Jake Ratcliffe",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
  "number": 8,
  "gp": 15,
  "goals": 12,
  "assists": 6,
  "points": 18,
  "pim": 12,
  "plusMinus": 7,
	"abr": "WAA"
}, {
  "name": "Andy Hart",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
  "number": 13,
  "gp": 15,
  "goals": 4,
  "assists": 20,
  "points": 24,
  "pim": 16,
  "plusMinus": 11,
	"abr": "WAA"
}, {
  "name": "Justin Daigle",
  "team": "West Auckland Admirals",
  "shoots": "Left",
  "position": "Defence",
  "number": 47,
  "gp": 16,
  "goals": 1,
  "assists": 2,
  "points": 3,
  "pim": 30,
  "plusMinus": 0,
	"abr": "WAA"
}, {
  "name": "Blake Jackson",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Defence",
  "number": 5,
  "gp": 15,
  "goals": 4,
  "assists": 8,
  "points": 12,
  "pim": 18,
  "plusMinus": 9,
	"abr": "WAA"
}, {
	"name": "Chris Eaden",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 43,
	"gp": 16,
	"goals": 14,
	"assists": 14,
	"points": 28,
	"pim": 10,
	"plusMinus": 9,
	"abr": "CRD"
}, {
	"name": "Brad Apps",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 21,
	"gp": 16,
	"goals": 4,
	"assists": 4,
	"points": 8,
	"pim": 8,
	"plusMinus": -9,
	"abr": "CRD"
}, {
	"name": "Alex Ashwell",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Shaun Brown",
	"team": "Canterbury Red Devils",
	"shoots": "Left",
	"position": "Forward",
	"number": 19,
	"gp": 16,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -3,
	"abr": "CRD"
}, {
	"name": "Liam Dallimore",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 14,
	"gp": 12,
	"goals": 4,
	"assists": 1,
	"points": 5,
	"pim": 4,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Alex Damm",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 0,
	"gp": 6,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Alex Egan",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 88,
	"gp": 7,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -1,
	"abr": "CRD"
}, {
	"name": "Justin Fuller",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 17,
	"gp": 14,
	"goals": 6,
	"assists": 7,
	"points": 13,
	"pim": 4,
	"plusMinus": 2,
	"abr": "CRD"
}, {
	"name": "Jeong Kim",
	"team": "Canterbury Red Devils",
	"shoots": "Left",
	"position": "Forward",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Luke Hill",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 18,
	"gp": 7,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Jaxson Lane",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 10,
	"gp": 16,
	"goals": 3,
	"assists": 5,
	"points": 8,
	"pim": 14,
	"plusMinus": -4,
	"abr": "CRD"
}, {
	"name": "Anton Purver",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 61,
	"gp": 16,
	"goals": 1,
	"assists": 1,
	"points": 2,
	"pim": 4,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Nik Stefanissin",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Moses Bygate-Smith",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"number": 12,
	"gp": 10,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -1,
	"abr": "CRD"
}, {
	"name": "Ryan Fraser",
	"team": "Canterbury Red Devils",
	"shoots": "Left",
	"position": "Defence",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Mason Kennedy",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"number": 8,
	"gp": 15,
	"goals": 0,
	"assists": 4,
	"points": 4,
	"pim": 14,
	"plusMinus": 1,
	"abr": "CRD"
}, {
	"name": "Henry Morley-Hall",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Kyle Nash",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"number": 79,
	"gp": 11,
	"goals": 0,
	"assists": 1,
	"points": 1,
	"pim": 4,
	"plusMinus": -1,
	"abr": "CRD"
}, {
	"name": "Mason Rees",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"number": 27,
	"gp": 4,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Michael Coleman",
	"team": "Canterbury Red Devils",
	"catches": "Left",
	"position": "GK",
	"number": 1,
	"gp": 9,
	"gaa": 4.49,
	"svs": 899,
	"abr": "CRD"
}, {
	"name": "Steven Coull",
	"team": "Canterbury Red Devils",
	"catches": "Left",
	"position": "GK",
	"number": 35,
	"gp": 2,
	"gaa": 13.02,
	"svs": 784,
	"abr": "CRD"
}, {
	"name": "Richard Bigsby",
	"team": "Canterbury Red Devils",
	"catches": "Left",
	"position": "GK",
	"number": 0,
	"gp": 0,
	"gaa": 0.00,
	"svs": 000,
	"abr": "CRD"
}, {
	"name": "Matt Schneider",
	"team": "Skycity Stampede",
	"shoots": "Left",
	"position": "Forward",
	"number": 4,
	"gp": 10,
	"goals": 14,
	"assists": 9,
	"points": 23,
	"pim": 2,
	"plusMinus": 12,
	"abr": "STP"
}, {
	"name": "Braden Lee",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"number": 12,
	"gp": 16,
	"goals": 7,
	"assists": 5,
	"points": 12,
	"pim": 8,
	"plusMinus": 10,
	"abr": "STP"
}, {
	"name": "Bert Haines",
	"team": "Skycity Stampede",
	"shoots": "Left",
	"position": "Defence",
	"number": 2,
	"gp": 16,
	"goals": 1,
	"assists": 2,
	"points": 3,
	"pim": 30,
	"plusMinus": 0,
	"abr": "STP"
}, {
	"name": "Hayden Argyle",
	"team": "Skycity Stampede",
	"shoots": "Left",
	"position": "Defence",
	"number": 22,
	"gp": 14,
	"goals": 2,
	"assists": 5,
	"points": 7,
	"pim": 49,
	"plusMinus": 9,
	"abr": "STP"
}, {
	"name": "Michael Attwell",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"number": 6,
	"gp": 15,
	"goals": 5,
	"assists": 8,
	"points": 13,
	"pim": 30,
	"plusMinus": -7,
	"abr": "BSW"
}, {
	"name": "K.C Ball",
	"team": "Botany Swarm",
	"shoots": "Left",
	"position": "Forward",
	"number": 14,
	"gp": 16,
	"goals": 0,
	"assists": 9,
	"points": 9,
	"pim": 6,
	"plusMinus": -8,
	"abr": "BSW"
}, {
	"name": "Oliver Hay",
	"team": "Botany Swarm",
	"shoots": "Left",
	"position": "Forward",
	"number": 21,
	"gp": 15,
	"goals": 2,
	"assists": 6,
	"points": 8,
	"pim": 47,
	"plusMinus": -7,
	"abr": "BSW"
}, {
	"name": "Logan Fraser",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Defence",
	"number": 24,
	"gp": 13,
	"goals": 2,
	"assists": 3,
	"points": 5,
	"pim": 4,
	"plusMinus": 3,
	"abr": "BSW"
}, {
	"name": "Joe Orr",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Forward",
	"number": 90,
	"gp": 13,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 8,
	"plusMinus": -9,
	"abr": "THU"
}, {
	"name": "Gints Leitis",
	"team": "Dunedin Thunder",
	"shoots": "Left",
	"position": "Forward",
	"number": 23,
	"gp": 14,
	"goals": 13,
	"assists": 14,
	"points": 27,
	"pim": 30,
	"plusMinus": -9,
	"abr": "THU"
}, {
	"name": "Connor Harrison",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Forward",
	"number": 8,
	"gp": 14,
	"goals": 3,
	"assists": 7,
	"points": 10,
	"pim": 45,
	"plusMinus": -11,
	"abr": "THU"
}, {
	"name": "Matas Barakauskas",
	"team": "Dunedin Thunder",
	"shoots": "Left",
	"position": "Defence",
	"number": 6,
	"gp": 12,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 2,
	"plusMinus": -5,
	"abr": "THU"
}])

p "Added #{Player.count} players"
